using System;
using Payments.Iso4217Currencies;

namespace Payments
{
	public static partial class Iso4217
	{
		public static readonly ICurrency AED = new Currency("AED", "?", 784, 100m);	//AED;784;2;UAE Dirham
		public static readonly ICurrency AFN = new Currency("AFN", "?", 971, 100m);	//AFN;971;2;Afghani
		public static readonly ICurrency ALL = new Currency("ALL", "?", 8, 100m);	//ALL;8;2;Lek
		public static readonly ICurrency AMD = new Currency("AMD", "?", 51, 100m);	//AMD;51;2;Armenian Dram
		public static readonly ICurrency ANG = new Currency("ANG", "?", 532, 100m);	//ANG;532;2;Netherlands Antillean Guilder
		public static readonly ICurrency AOA = new Currency("AOA", "?", 973, 100m);	//AOA;973;2;Kwanza
		public static readonly ICurrency ARS = new Currency("ARS", "?", 32, 100m);	//ARS;32;2;Argentine Peso
		public static readonly ICurrency AUD = new Currency("AUD", "?", 36, 100m);	//AUD;36;2;Australian Dollar
		public static readonly ICurrency AWG = new Currency("AWG", "?", 533, 100m);	//AWG;533;2;Aruban Guilder
		public static readonly ICurrency AZN = new Currency("AZN", "?", 944, 100m);	//AZN;944;2;Azerbaijanian Manat
		public static readonly ICurrency BAM = new Currency("BAM", "?", 977, 100m);	//BAM;977;2;Convertible Mark
		public static readonly ICurrency BBD = new Currency("BBD", "?", 52, 100m);	//BBD;52;2;Barbados Dollar
		public static readonly ICurrency BDT = new Currency("BDT", "?", 50, 100m);	//BDT;50;2;Taka
		public static readonly ICurrency BGN = new Currency("BGN", "?", 975, 100m);	//BGN;975;2;Bulgarian Lev
		public static readonly ICurrency BHD = new Currency("BHD", "?", 48, 100m);	//BHD;48;3;Bahraini Dinar
		public static readonly ICurrency BIF = new Currency("BIF", "?", 108, 100m);	//BIF;108;0;Burundi Franc
		public static readonly ICurrency BMD = new Currency("BMD", "?", 60, 100m);	//BMD;60;2;Bermudian Dollar
		public static readonly ICurrency BND = new Currency("BND", "?", 96, 100m);	//BND;96;2;Brunei Dollar
		public static readonly ICurrency BOB = new Currency("BOB", "?", 68, 100m);	//BOB;68;2;Boliviano
		public static readonly ICurrency BOV = new Currency("BOV", "?", 984, 100m);	//BOV;984;2;Mvdol
		public static readonly ICurrency BRL = new Currency("BRL", "?", 986, 100m);	//BRL;986;2;Brazilian Real
		public static readonly ICurrency BSD = new Currency("BSD", "?", 44, 100m);	//BSD;44;2;Bahamian Dollar
		public static readonly ICurrency BTN = new Currency("BTN", "?", 64, 100m);	//BTN;64;2;Ngultrum
		public static readonly ICurrency BWP = new Currency("BWP", "?", 72, 100m);	//BWP;72;2;Pula
		public static readonly ICurrency BYR = new Currency("BYR", "?", 974, 100m);	//BYR;974;0;Belarussian Ruble
		public static readonly ICurrency BZD = new Currency("BZD", "?", 84, 100m);	//BZD;84;2;Belize Dollar
		public static readonly ICurrency CAD = new Currency("CAD", "?", 124, 100m);	//CAD;124;2;Canadian Dollar
		public static readonly ICurrency CDF = new Currency("CDF", "?", 976, 100m);	//CDF;976;2;Congolese Franc
		public static readonly ICurrency CHE = new Currency("CHE", "?", 947, 100m);	//CHE;947;2;WIR Euro
		public static readonly ICurrency CHF = new Currency("CHF", "?", 756, 100m);	//CHF;756;2;Swiss Franc
		public static readonly ICurrency CHW = new Currency("CHW", "?", 948, 100m);	//CHW;948;2;WIR Franc
		public static readonly ICurrency CLF = new Currency("CLF", "?", 990, 100m);	//CLF;990;0;Unidades de fomento
		public static readonly ICurrency CLP = new Currency("CLP", "?", 152, 100m);	//CLP;152;0;Chilean Peso
		public static readonly ICurrency CNY = new Currency("CNY", "?", 156, 100m);	//CNY;156;2;Yuan Renminbi
		public static readonly ICurrency COP = new Currency("COP", "?", 170, 100m);	//COP;170;2;Colombian Peso
		public static readonly ICurrency COU = new Currency("COU", "?", 970, 100m);	//COU;970;2;Unidad de Valor Real
		public static readonly ICurrency CRC = new Currency("CRC", "?", 188, 100m);	//CRC;188;2;Costa Rican Colon
		public static readonly ICurrency CUC = new Currency("CUC", "?", 931, 100m);	//CUC;931;2;Peso Convertible
		public static readonly ICurrency CUP = new Currency("CUP", "?", 192, 100m);	//CUP;192;2;Cuban Peso
		public static readonly ICurrency CVE = new Currency("CVE", "?", 132, 100m);	//CVE;132;2;Cape Verde Escudo
		public static readonly ICurrency CZK = new Currency("CZK", "?", 203, 100m);	//CZK;203;2;Czech Koruna
		public static readonly ICurrency DJF = new Currency("DJF", "?", 262, 100m);	//DJF;262;0;Djibouti Franc
		public static readonly ICurrency DKK = new Currency("DKK", "?", 208, 100m);	//DKK;208;2;Danish Krone
		public static readonly ICurrency DOP = new Currency("DOP", "?", 214, 100m);	//DOP;214;2;Dominican Peso
		public static readonly ICurrency DZD = new Currency("DZD", "?", 12, 100m);	//DZD;12;2;Algerian Dinar
		public static readonly ICurrency EGP = new Currency("EGP", "?", 818, 100m);	//EGP;818;2;Egyptian Pound
		public static readonly ICurrency ERN = new Currency("ERN", "?", 232, 100m);	//ERN;232;2;Nakfa
		public static readonly ICurrency ETB = new Currency("ETB", "?", 230, 100m);	//ETB;230;2;Ethiopian Birr
		public static readonly ICurrency EUR = new Currency("EUR", "?", 978, 100m);	//EUR;978;2;Euro
		public static readonly ICurrency FJD = new Currency("FJD", "?", 242, 100m);	//FJD;242;2;Fiji Dollar
		public static readonly ICurrency FKP = new Currency("FKP", "?", 238, 100m);	//FKP;238;2;Falkland Islands Pound
		public static readonly ICurrency GBP = new Currency("GBP", "?", 826, 100m);	//GBP;826;2;Pound Sterling
		public static readonly ICurrency GEL = new Currency("GEL", "?", 981, 100m);	//GEL;981;2;Lari
		public static readonly ICurrency GHS = new Currency("GHS", "?", 936, 100m);	//GHS;936;2;Cedi
		public static readonly ICurrency GIP = new Currency("GIP", "?", 292, 100m);	//GIP;292;2;Gibraltar Pound
		public static readonly ICurrency GMD = new Currency("GMD", "?", 270, 100m);	//GMD;270;2;Dalasi
		public static readonly ICurrency GNF = new Currency("GNF", "?", 324, 100m);	//GNF;324;0;Guinea Franc
		public static readonly ICurrency GTQ = new Currency("GTQ", "?", 320, 100m);	//GTQ;320;2;Quetzal
		public static readonly ICurrency GYD = new Currency("GYD", "?", 328, 100m);	//GYD;328;2;Guyana Dollar
		public static readonly ICurrency HKD = new Currency("HKD", "?", 344, 100m);	//HKD;344;2;Hong Kong Dollar
		public static readonly ICurrency HNL = new Currency("HNL", "?", 340, 100m);	//HNL;340;2;Lempira
		public static readonly ICurrency HRK = new Currency("HRK", "?", 191, 100m);	//HRK;191;2;Croatian Kuna
		public static readonly ICurrency HTG = new Currency("HTG", "?", 332, 100m);	//HTG;332;2;Gourde
		public static readonly ICurrency HUF = new Currency("HUF", "?", 348, 100m);	//HUF;348;2;Forint
		public static readonly ICurrency IDR = new Currency("IDR", "?", 360, 100m);	//IDR;360;2;Rupiah
		public static readonly ICurrency ILS = new Currency("ILS", "?", 376, 100m);	//ILS;376;2;New Israeli Sheqel
		public static readonly ICurrency INR = new Currency("INR", "?", 356, 100m);	//INR;356;2;Indian Rupee
		public static readonly ICurrency IQD = new Currency("IQD", "?", 368, 100m);	//IQD;368;3;Iraqi Dinar
		public static readonly ICurrency IRR = new Currency("IRR", "?", 364, 100m);	//IRR;364;2;Iranian Rial
		public static readonly ICurrency ISK = new Currency("ISK", "?", 352, 100m);	//ISK;352;0;Iceland Krona
		public static readonly ICurrency JMD = new Currency("JMD", "?", 388, 100m);	//JMD;388;2;Jamaican Dollar
		public static readonly ICurrency JOD = new Currency("JOD", "?", 400, 100m);	//JOD;400;3;Jordanian Dinar
		public static readonly ICurrency JPY = new Currency("JPY", "?", 392, 100m);	//JPY;392;0;Yen
		public static readonly ICurrency KES = new Currency("KES", "?", 404, 100m);	//KES;404;2;Kenyan Shilling
		public static readonly ICurrency KGS = new Currency("KGS", "?", 417, 100m);	//KGS;417;2;Som
		public static readonly ICurrency KHR = new Currency("KHR", "?", 116, 100m);	//KHR;116;2;Riel
		public static readonly ICurrency KMF = new Currency("KMF", "?", 174, 100m);	//KMF;174;0;Comoro Franc
		public static readonly ICurrency KPW = new Currency("KPW", "?", 408, 100m);	//KPW;408;2;North Korean Won
		public static readonly ICurrency KRW = new Currency("KRW", "?", 410, 100m);	//KRW;410;0;Won
		public static readonly ICurrency KWD = new Currency("KWD", "?", 414, 100m);	//KWD;414;3;Kuwaiti Dinar
		public static readonly ICurrency KYD = new Currency("KYD", "?", 136, 100m);	//KYD;136;2;Cayman Islands Dollar
		public static readonly ICurrency KZT = new Currency("KZT", "?", 398, 100m);	//KZT;398;2;Tenge
		public static readonly ICurrency LAK = new Currency("LAK", "?", 418, 100m);	//LAK;418;2;Kip
		public static readonly ICurrency LBP = new Currency("LBP", "?", 422, 100m);	//LBP;422;2;Lebanese Pound
		public static readonly ICurrency LKR = new Currency("LKR", "?", 144, 100m);	//LKR;144;2;Sri Lanka Rupee
		public static readonly ICurrency LRD = new Currency("LRD", "?", 430, 100m);	//LRD;430;2;Liberian Dollar
		public static readonly ICurrency LSL = new Currency("LSL", "?", 426, 100m);	//LSL;426;2;Loti
		public static readonly ICurrency LTL = new Currency("LTL", "?", 440, 100m);	//LTL;440;2;Lithuanian Litas
		public static readonly ICurrency LVL = new Currency("LVL", "?", 428, 100m);	//LVL;428;2;Latvian Lats
		public static readonly ICurrency LYD = new Currency("LYD", "?", 434, 100m);	//LYD;434;3;Libyan Dinar
		public static readonly ICurrency MAD = new Currency("MAD", "?", 504, 100m);	//MAD;504;2;Moroccan Dirham
		public static readonly ICurrency MDL = new Currency("MDL", "?", 498, 100m);	//MDL;498;2;Moldovan Leu
		public static readonly ICurrency MGA = new Currency("MGA", "?", 969, 100m);	//MGA;969;2;Malagasy Ariary
		public static readonly ICurrency MKD = new Currency("MKD", "?", 807, 100m);	//MKD;807;2;Denar
		public static readonly ICurrency MMK = new Currency("MMK", "?", 104, 100m);	//MMK;104;2;Kyat
		public static readonly ICurrency MNT = new Currency("MNT", "?", 496, 100m);	//MNT;496;2;Tugrik
		public static readonly ICurrency MOP = new Currency("MOP", "?", 446, 100m);	//MOP;446;2;Pataca
		public static readonly ICurrency MRO = new Currency("MRO", "?", 478, 100m);	//MRO;478;2;Ouguiya
		public static readonly ICurrency MUR = new Currency("MUR", "?", 480, 100m);	//MUR;480;2;Mauritius Rupee
		public static readonly ICurrency MVR = new Currency("MVR", "?", 462, 100m);	//MVR;462;2;Rufiyaa
		public static readonly ICurrency MWK = new Currency("MWK", "?", 454, 100m);	//MWK;454;2;Kwacha
		public static readonly ICurrency MXN = new Currency("MXN", "?", 484, 100m);	//MXN;484;2;Mexican Peso
		public static readonly ICurrency MXV = new Currency("MXV", "?", 979, 100m);	//MXV;979;2;Mexican Unidad de Inversion (UDI)
		public static readonly ICurrency MYR = new Currency("MYR", "?", 458, 100m);	//MYR;458;2;Malaysian Ringgit
		public static readonly ICurrency MZN = new Currency("MZN", "?", 943, 100m);	//MZN;943;2;Metical
		public static readonly ICurrency NAD = new Currency("NAD", "?", 516, 100m);	//NAD;516;2;Namibia Dollar
		public static readonly ICurrency NGN = new Currency("NGN", "?", 566, 100m);	//NGN;566;2;Naira
		public static readonly ICurrency NIO = new Currency("NIO", "?", 558, 100m);	//NIO;558;2;Cordoba Oro
		public static readonly ICurrency NOK = new Currency("NOK", "?", 578, 100m);	//NOK;578;2;Norwegian Krone
		public static readonly ICurrency NPR = new Currency("NPR", "?", 524, 100m);	//NPR;524;2;Nepalese Rupee
		public static readonly ICurrency NZD = new Currency("NZD", "?", 554, 100m);	//NZD;554;2;New Zealand Dollar
		public static readonly ICurrency OMR = new Currency("OMR", "?", 512, 100m);	//OMR;512;3;Rial Omani
		public static readonly ICurrency PAB = new Currency("PAB", "?", 590, 100m);	//PAB;590;2;Balboa
		public static readonly ICurrency PEN = new Currency("PEN", "?", 604, 100m);	//PEN;604;2;Nuevo Sol
		public static readonly ICurrency PGK = new Currency("PGK", "?", 598, 100m);	//PGK;598;2;Kina
		public static readonly ICurrency PHP = new Currency("PHP", "?", 608, 100m);	//PHP;608;2;Philippine Peso
		public static readonly ICurrency PKR = new Currency("PKR", "?", 586, 100m);	//PKR;586;2;Pakistan Rupee
		public static readonly ICurrency PLN = new Currency("PLN", "?", 985, 100m);	//PLN;985;2;Zloty
		public static readonly ICurrency PYG = new Currency("PYG", "?", 600, 100m);	//PYG;600;0;Guarani
		public static readonly ICurrency QAR = new Currency("QAR", "?", 634, 100m);	//QAR;634;2;Qatari Rial
		public static readonly ICurrency RON = new Currency("RON", "?", 946, 100m);	//RON;946;2;Leu
		public static readonly ICurrency RSD = new Currency("RSD", "?", 941, 100m);	//RSD;941;2;Serbian Dinar
		public static readonly ICurrency RUB = new Currency("RUB", "?", 643, 100m);	//RUB;643;2;Russian Ruble
		public static readonly ICurrency RWF = new Currency("RWF", "?", 646, 100m);	//RWF;646;0;Rwanda Franc
		public static readonly ICurrency SAR = new Currency("SAR", "?", 682, 100m);	//SAR;682;2;Saudi Riyal
		public static readonly ICurrency SBD = new Currency("SBD", "?", 90, 100m);	//SBD;90;2;Solomon Islands Dollar
		public static readonly ICurrency SCR = new Currency("SCR", "?", 690, 100m);	//SCR;690;2;Seychelles Rupee
		public static readonly ICurrency SDG = new Currency("SDG", "?", 938, 100m);	//SDG;938;2;Sudanese Pound
		public static readonly ICurrency SEK = new Currency("SEK", "?", 752, 100m);	//SEK;752;2;Swedish Krona
		public static readonly ICurrency SGD = new Currency("SGD", "?", 702, 100m);	//SGD;702;2;Singapore Dollar
		public static readonly ICurrency SHP = new Currency("SHP", "?", 654, 100m);	//SHP;654;2;Saint Helena Pound
		public static readonly ICurrency SLL = new Currency("SLL", "?", 694, 100m);	//SLL;694;2;Leone
		public static readonly ICurrency SOS = new Currency("SOS", "?", 706, 100m);	//SOS;706;2;Somali Shilling
		public static readonly ICurrency SRD = new Currency("SRD", "?", 968, 100m);	//SRD;968;2;Surinam Dollar
		public static readonly ICurrency STD = new Currency("STD", "?", 678, 100m);	//STD;678;2;Dobra
		public static readonly ICurrency SVC = new Currency("SVC", "?", 222, 100m);	//SVC;222;2;El Salvador Colon
		public static readonly ICurrency SYP = new Currency("SYP", "?", 760, 100m);	//SYP;760;2;Syrian Pound
		public static readonly ICurrency SZL = new Currency("SZL", "?", 748, 100m);	//SZL;748;2;Lilangeni
		public static readonly ICurrency THB = new Currency("THB", "?", 764, 100m);	//THB;764;2;Baht
		public static readonly ICurrency TJS = new Currency("TJS", "?", 972, 100m);	//TJS;972;2;Somoni
		public static readonly ICurrency TMT = new Currency("TMT", "?", 934, 100m);	//TMT;934;2;New Manat
		public static readonly ICurrency TND = new Currency("TND", "?", 788, 100m);	//TND;788;3;Tunisian Dinar
		public static readonly ICurrency TOP = new Currency("TOP", "?", 776, 100m);	//TOP;776;2;Pa’anga
		public static readonly ICurrency TRY = new Currency("TRY", "?", 949, 100m);	//TRY;949;2;Turkish Lira
		public static readonly ICurrency TTD = new Currency("TTD", "?", 780, 100m);	//TTD;780;2;Trinidad and Tobago Dollar
		public static readonly ICurrency TWD = new Currency("TWD", "?", 901, 100m);	//TWD;901;2;New Taiwan Dollar
		public static readonly ICurrency TZS = new Currency("TZS", "?", 834, 100m);	//TZS;834;2;Tanzanian Shilling
		public static readonly ICurrency UAH = new Currency("UAH", "?", 980, 100m);	//UAH;980;2;Hryvnia
		public static readonly ICurrency UGX = new Currency("UGX", "?", 800, 100m);	//UGX;800;2;Uganda Shilling
		public static readonly ICurrency USD = new Currency("USD", "?", 840, 100m);	//USD;840;2;US Dollar
		public static readonly ICurrency USN = new Currency("USN", "?", 997, 100m);	//USN;997;2;US Dollar (Next day)
		public static readonly ICurrency USS = new Currency("USS", "?", 998, 100m);	//USS;998;2;US Dollar (Same day)
		public static readonly ICurrency UYI = new Currency("UYI", "?", 940, 100m);	//UYI;940;0;Uruguay Peso en Unidades Indexadas (URUIURUI)
		public static readonly ICurrency UYU = new Currency("UYU", "?", 858, 100m);	//UYU;858;2;Peso Uruguayo
		public static readonly ICurrency UZS = new Currency("UZS", "?", 860, 100m);	//UZS;860;2;Uzbekistan Sum
		public static readonly ICurrency VEF = new Currency("VEF", "?", 937, 100m);	//VEF;937;2;Bolivar Fuerte
		public static readonly ICurrency VND = new Currency("VND", "?", 704, 100m);	//VND;704;0;Dong
		public static readonly ICurrency VUV = new Currency("VUV", "?", 548, 100m);	//VUV;548;0;Vatu
		public static readonly ICurrency WST = new Currency("WST", "?", 882, 100m);	//WST;882;2;Tala
		public static readonly ICurrency XAF = new Currency("XAF", "?", 950, 100m);	//XAF;950;0;CFA Franc BEAC
		public static readonly ICurrency XAG = new Currency("XAG", "?", 961, 100m);	//XAG;961;N.A.;Silver
		public static readonly ICurrency XAU = new Currency("XAU", "?", 959, 100m);	//XAU;959;N.A.;Gold
		public static readonly ICurrency XBA = new Currency("XBA", "?", 955, 100m);	//XBA;955;N.A.;EURCO
		public static readonly ICurrency XBB = new Currency("XBB", "?", 956, 100m);	//XBB;956;N.A.;EMU-6
		public static readonly ICurrency XBC = new Currency("XBC", "?", 957, 100m);	//XBC;957;N.A.;EUA-9
		public static readonly ICurrency XBD = new Currency("XBD", "?", 958, 100m);	//XBD;958;N.A.;EUA-17
		public static readonly ICurrency XCD = new Currency("XCD", "?", 951, 100m);	//XCD;951;2;East Caribbean Dollar
		public static readonly ICurrency XDR = new Currency("XDR", "?", 960, 100m);	//XDR;960;N.A.;SDR (Special Drawing Right)
		public static readonly ICurrency XFU = new Currency("XFU", "?", -1, 100m);	//XFU;-1;N.A.;UIC-Franc
		public static readonly ICurrency XOF = new Currency("XOF", "?", 952, 100m);	//XOF;952;0;CFA Franc BCEAO
		public static readonly ICurrency XPD = new Currency("XPD", "?", 964, 100m);	//XPD;964;N.A;Palladium
		public static readonly ICurrency XPF = new Currency("XPF", "?", 953, 100m);	//XPF;953;0;CFP Franc
		public static readonly ICurrency XPT = new Currency("XPT", "?", 962, 100m);	//XPT;962;N.A.;Platinum
		public static readonly ICurrency XSU = new Currency("XSU", "?", 994, 100m);	//XSU;994;N.A.;Sucre
		public static readonly ICurrency XTS = new Currency("XTS", "?", 963, 100m);	//XTS;963;N.A.;Codes for testing purposes
		public static readonly ICurrency XXX = new Currency("XXX", "?", 999, 100m);	//XXX;999;N.A.;No currency
		public static readonly ICurrency YER = new Currency("YER", "?", 886, 100m);	//YER;886;2;Yemeni Rial
		public static readonly ICurrency ZAR = new Currency("ZAR", "?", 710, 100m);	//ZAR;710;2;South African Rand
		public static readonly ICurrency ZMK = new Currency("ZMK", "?", 894, 100m);	//ZMK;894;2;Zambian Kwacha
		public static readonly ICurrency ZWL = new Currency("ZWL", "?", 932, 100m);	//ZWL;932;2;Zimbabwe Dollar

	}
}
